beerdb/urls.py
from django.conf.urls.defaults import *

from beerdb.views import BeerDetailView, BeerListView, BrewerDetailView, BrewerListView, UserDetailView, beer_rate

urlpatterns = patterns('',
  # User ratings
  (r'^user/(?P<slug>[^/]+)/$', UserDetailView.as_view(), {}, 'beerdb_user_detail'),
  
  # Beers
  (r'^$', BeerListView.as_view(), {}, 'beerdb_beer_list'),
  (r'^(?P<brewer__slug>[^/]+)/(?P<slug>[^/]+)/$', BeerDetailView.as_view(), {}, 'beerdb_beer_detail'),
  (r'^(?P<brewer_slug>[^/]+)/(?P<beer_slug>[^/]+)/rate/$', beer_rate, {}, 'beerdb_beer_rate'),
  
  # Brewers
  (r'^brewers/$', BrewerListView.as_view(), {}, 'beerdb_brewer_list'),
  (r'^(?P<slug>[^/]+)/$', BrewerDetailView.as_view(), {}, 'beerdb_brewer_detail'),
)

beerdb/models.py
from autoslug.fields import AutoSlugField

from django.contrib import admin
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import post_save
from django.utils.translation import ugettext_lazy as _

class Rating(models.Model):
  slug = AutoSlugField(populate_from='name', unique=True, default='', help_text=_('Slug value for the rating.'))
  name = models.CharField(max_length=100, unique=True, help_text=_('Name of the rating for display purposes.'))
  order = models.PositiveIntegerField(unique=True, help_text=_('The order in which ratings are displayed.'))
  
  class Meta:
    ordering = ('order',)
    verbose_name = _('rating')
    verbose_name_plural = _('ratings')
  
  def __unicode__(self):
    return self.name

class URLSite(models.Model):
  name = models.CharField(max_length=250, help_text=_('The display name for the domain.'))
  domain = models.CharField(max_length=250, help_text=_('The domain of the related site.'))
  
  class Meta:
    verbose_name = _('URL site')
    verbose_name_plural = _('URL sites')
  
  def __unicode__(self):
    return self.name + ' (' + self.domain + ')'

class URL(models.Model):
  url = models.CharField(max_length=500, help_text=_('The URI path on the related site.'))
  site = models.ForeignKey(URLSite, help_text=_('The related site for this URL/URI.'))
  
  class Meta:
    verbose_name = _('URL')
    verbose_name_plural = _('URLs')
  
  def __unicode__(self):
    return 'http://%s%s' % (self.site.domain, self.url,)

class Brewer(models.Model):
  slug = AutoSlugField(populate_from='name', unique=True, help_text=_('Slug value for brewer based on the name.'))
  name = models.CharField(max_length=250, help_text=_('Name of the brewer.'))
  
  class Meta:
    ordering = ('name',)
    verbose_name = _('brewer')
    verbose_name_plural = _('brewers')
  
  def __unicode__(self):
    return unicode(self.name)
  
  def get_absolute_url(self):
    return reverse('view_brewer', args=[self.slug])
  
  def get_api_url(self):
    return reverse('beerdb_api_brewer', args=[self.slug])

class Beer(models.Model):
  """
  Beer storage.
  """
  brewer = models.ForeignKey(Brewer, help_text=_('The brewer for this beer.'))
  user = models.ManyToManyField(User, through='UserRating', help_text=_('User ratings for this beer.'))
  url = models.ManyToManyField(URL, help_text=_('External URLs for this beer.'))
  slug = AutoSlugField(populate_from='name', unique_with='brewer', help_text=_('The unique slug for the given beer.'))
  name = models.CharField(max_length=250, help_text=_('The name of the beer.'))
  
  class Meta:
    ordering = ('brewer__name', 'name',)
    verbose_name = _('beer')
    verbose_name_plural = _('beers')
  
  def __unicode__(self):
    return '%s by %s' % (unicode(self.name), unicode(self.brewer.name),)
  
  def get_user_rating(self, username):
    return UserRating.objects.get(beer=self, user__username=username).rating
  
  def get_absolute_url(self):
    return reverse('view_beer', args=[self.brewer.slug, self.slug])
  
  def get_api_url(self):
    return reverse('beerdb_api_beer', args=[self.brewer.slug, self.slug])

class UserRating(models.Model):
  user = models.ForeignKey(User)
  beer = models.ForeignKey(Beer)
  rating = models.ForeignKey(Rating, blank=True, null=True, help_text=_('A rating for this beer by the given user.'))
  note = models.TextField(default='', blank=True, verbose_name='Notes', help_text=_('Notes on this beer by the given user.'))
  date_added = models.DateTimeField(auto_now_add=True, help_text=_('The date on which the user rated the beer.'))
  date_modified = models.DateTimeField(auto_now=True, help_text=_('The last modified date for this rating and/or note.'))
  
  class Meta:
    ordering = ('user', '-date_modified', '-date_added', '-id',)
    verbose_name = _('user beer rating')
    verbose_name_plural = _('user beer ratings')
  
  def __unicode__(self):
    return self.beer.name + ' rating by ' + self.user.username
  
  def get_absolute_url(self):
    return reverse('beerdb_beer_rate', args=[self.beer.brewer.slug, self.beer.slug])

beerdb/templates/beerdb/_form_field.html
{{ field.errors }}
<p><label for="id_{{ field.name }}">{{ field.label }}<br>{{ field }}</label></p>
<p class="help_text">{{ field.help_text }}</p>

beerdb/templates/beerdb/beer_detail.html
{% extends 'base.html' %}

{% load url from future %}

{% block title %}{{ beer.name }}{% endblock %}

{% block content %}
  <h1>{{ beer.name }}</h1>
  <h2>by <a href="{% url 'beerdb_brewer_detail' beer.brewer.slug %}">{{ beer.brewer.name }}</a></h2>
  
  {# Print this user's rating/review #}
  {% if user_rating %}
    <h3>Your Review</h3>
    {# Rating value #}
    {% if user_rating.rating %}
      <p>{{ user_rating.rating }}</p>
    {% else %}
      <p><em>No rating</em></p>
    {% endif %}
    
    {# Rating note #}
    {% if user_rating.note %}
      <p>{{ user_rating.note }}</p>
    {% endif %}
  {% endif %}
  
  {# Link to create or update rating #}
  <p><a href="{% url 'beerdb_beer_rate' beer.brewer.slug beer.slug %}">{% if user_rating %}Update your rating{% else %}Rate this beer{% endif %}</a></p>
  
  <h3>Other User Ratings</h3>
  <ul>
    {# Iterate through other user's ratings of this beer #}
    {% for user_rating in other_user_ratings %}
      {% ifchanged user_rating.rating %}
        {% if forloop.counter > 1 %}</ul></li>{% endif %}
        <li>{{ user_rating.rating }}<ul>
      {% endifchanged %}
      
      {# Print username #}
      <li><a href="{% url 'beerdb_user_detail' user_rating.user.username %}">{{ user_rating.user }}</a></li>
      
      {# Close list on last iteration #}
      {% if forloop.last %}</ul></li>{% endif %}
    {% empty %}
      <li><em>No ratings available</em></li>
    {% endfor %}
  </ul>
  
  <h3>Links</h3>
  <ul>
    {% for url in beer.url.all %}
      <li><a href="{{ url }}" rel="nofollow">{{ url.site.name }}</a></li>
    {% empty %}
      <li><em>No links available</em></li>
    {% endfor %}
  </ul>
{% endblock %}

beerdb/templates/beerdb/beer_list.html
{% extends "base.html" %}

{% load url from future %}

{% block title %}Beer List{% endblock %}

{% block content %}
  <ul>
    {% for beer in beers %}
      {% ifchanged beer.brewer.id %}
        {% if forloop.counter > 1 %}</ul></li>{% endif %}
        <li>{{ beer.brewer.name }}<ul>
      {% endifchanged %}
      <li><a href="{% url 'beerdb_beer_detail' beer.brewer.slug beer.slug %}">{{ beer.name }}</a></li>
      {% if forloop.last %}</li></ul>{% endif %}
    {% endfor %}
  </ul>
{% endblock %}

beerdb/templates/beerdb/beer_rate.html
{% extends 'base.html' %}

{% load url from future %}

{% block title %}Rate {{ beer.name }}{% endblock %}

{% block content %}
  <h1>{{ beer.name }}</h1>
  <h2>by <a href="{% url 'beerdb_brewer_detail' beer.brewer.slug %}">{{ beer.brewer.name }}</a></h2>
  
  <form action="" method="post">
    {{ user_rating_form.non_field_errors }}
    
    {% for field in user_rating_form.visible_fields %}
      {% include 'beerdb/_form_field.html' %}
    {% endfor %}
    
    {% for field in user_rating_form.hidden_fields %}
      {{ field }}
    {% endfor %}
    
    <button type="submit">Rate</button>
  </form>
{% endblock %}

beerdb/templates/beerdb/brewer_detail.html
{% extends 'base.html' %}

{% load url from future %}

{% block title %}{{ brewer.name }}{% endblock %}

{% block content %}
  <h1>{{ brewer.name }}</h1>

  {% if brewer.beer_set.all.count %}
    <ul>
      {% for beer in brewer.beer_set.all %}
        <li><a href="{% url 'beerdb_beer_detail' brewer.slug beer.slug %}">{{ beer.name }}</a></li>
      {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

beerdb/templates/beerdb/brewer_list.html
{% extends "base.html" %}

{% block title %}Brewer List{% endblock %}

{% block content %}
  <ul>
    {% for brewer in brewers %}
      <li>{{ brewer.name }}</li>
    {% endfor %}
  </ul>
{% endblock %}